sudo: false
language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run build
  - echo "snappy.zhaofeng.li" > dist/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

notifications:
  webhooks: https://app.fossa.io/hooks/travisci
